### ISSUE TITLE
Reduce testing time in  travis

### ISSUE THREAD

**Issue by Radi85** [Radi85/Comment#112]
### Change Type
[ ] Refactor/Enhancement
[ ] Testing
[x] CI/CD
[ ] Other

### Proposed Changes

Reduce the testing time in travis by reducing the number of python and django compatibility versions.
We can use the most first and most recent version that our app is compatible with.
#### For python:
- 3.6
- 3.8

#### django:
- 2.1
- 3.1
- django-master

**Comment by abhiabhi94** [comment]
for documentation specific changes, you may use the [[skip ci]](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build) in commit message to allow it to pass. This [link](https://reflectoring.io/skip-ci-build/#using-a-git-diff-in-the-ci-build) suggests another option.

Regarding the testing time on travis, someone it does takes a lot of time but this is usually not due to us but something because of them. The tests not take more than 10min to run on all supported versions as of now.  I had an email from them that they are going to transfer all repositories to travis-ci.com and the org version will be dead by the end of this year. Maybe that could be a reason.

**Comment by abhiabhi94** [comment]
Also, the issue template formatting needs to be updated, I have edited the comment on this one, but it needs to be done in the codebase to be fixed for future.

**Comment by Radi85** [comment]
> for documentation specific changes, you may use the [[skip ci]](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build) in commit message to allow it to pass. This [link](https://reflectoring.io/skip-ci-build/#using-a-git-diff-in-the-ci-build) suggests another option.
> 
> Regarding the testing time on travis, someone it does takes a lot of time but this is usually not due to us but something because of them. The tests not take more than 10min to run on all supported versions as of now. I had an email from them that they are going to transfer all repositories to travis-ci.com and the org version will be dead by the end of this year. Maybe that could be a reason.

Thanks for the info.
In fact why do we need to check the compatibility for every version? What I have mentioned above is enough to cover the versions in between.

**Comment by Radi85** [comment]
> Also, the issue template formatting needs to be updated, I have edited the comment on this one, but it needs to be done in the codebase to be fixed for future.

What needs to be updated?

**Comment by abhiabhi94** [comment]
you have changed my edits. my version would reflect the to-do list as:

>-  [ ] Refactor/Enhancement
- [ ] Testing
- [x] CI/CD
- [ ] Other

while as of now, you can see the to-do list is not rendered correctly.

**Comment by Radi85** [comment]
> > What needs to be updated?
> 
> you have changed my edit. my version would reflect the to-do list as:
> 
> > * [ ]  Refactor/Enhancement
> > * [ ]  Testing
> > * [x]  CI/CD
> > * [ ]  Other
> 
> while as of now, you can see the to-do list is not rendered correctly.

😄 I have updated it already.

**Comment by abhiabhi94** [comment]
#### Radico's TODO

![image](https://user-images.githubusercontent.com/13880786/101282456-480c0b80-37fb-11eb-965b-a01947e8d630.png)

#### Abhyudai's TODO

![image](https://user-images.githubusercontent.com/13880786/101282480-696cf780-37fb-11eb-846e-374355508956.png)

**Comment by Radi85** [comment]
Ahhh 😄 , in face this is not a TODO list but just an option of the change type. TODO means that all items should be implemented and this is not the case in issue templates.
Also I list the choices similarly to Github's auto generated issue templates.
