### ISSUE TITLE
Can not migrate

### ISSUE THREAD

**Issue by ZeroCoolHacker** [Radi85/Comment#114]
### Environment
* python 3.8.6
* django 3.1.3
* django-comments-dab

### Describe the bug
I am not able to migrate the app due to some error in __init__ file of comment app. It searches for VERSION file which isn't there. I get this error
```File "/home/shahzaib/Public/omniapps/elearning/env/lib/python3.8/site-packages/comment/__init__.py", line 15, in <module>
    __version__ = _get_version()
  File "/home/shahzaib/Public/omniapps/elearning/env/lib/python3.8/site-packages/comment/__init__.py", line 6, in _get_version
    with open(os.path.join(_parent_project_dir, 'VERSION')) as version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shahzaib/Public/omniapps/elearning/env/lib/python3.8/site-packages/VERSION'

```
I can't even run the server now. This error shows up on every command

### Steps To Reproduce
1. pip install django-comments-dab
2. add 'comment' to installed apps
3. Run ```python manage.py migrate comment```

### Expected behavior
The app should create the tables for the comment models

### Screenshots
![image](https://user-images.githubusercontent.com/18724529/101316652-b8a83c00-387e-11eb-8017-c2b4b5ba83ae.png)
![image](https://user-images.githubusercontent.com/18724529/101316679-c3fb6780-387e-11eb-9900-f0182896441f.png)

**Comment by abhiabhi94** [comment]
Thanks for the report. This is because the VERSION file is not downloaded when installing from pypi. I try to fix this when I have some more time today.

Till then if you want you this app to work, you may clone the latest version from the github.

**Comment by Radi85** [comment]
> Till then if you want you this app to work, you may clone the latest version from the github.

Since this is a critical issue, I will push the fix in few hours and redeploy the app with fix version `2.5.1`.

**Comment by ZeroCoolHacker** [comment]
@Radi85  Thank you so much for the support

**Comment by Radi85** [comment]
@ZeroCoolHacker,
You are welcome! and thanks for your feedback.
