### ISSUE TITLE
Better UserSerializer

### ISSUE THREAD

**Issue by ZeroCoolHacker** [Radi85/Comment#117]
### Environment
* Python version: 3.8
* django-comments-dab version: 2.5.1 

### Proposed Functionality
The get_user_fields function used in UserSerializer has the hardcoded field of username. In some projects we don't use username as the primary field. I had to change the function to make it work with my software.

https://github.com/Radi85/Comment/blob/1c2359e2c11f6efa4d62ba4d260848b3c8e37ead/comment/api/serializers.py#L22-L28

I suggest something like this. 

```python
def get_user_fields():
    user_model = get_user_model()
    fields = user_model._meta.get_fields()
    for field in fields:
        if hasattr(field, "upload_to"):
            return list(set('id', user_model.USERNAME_FIELD, 'email', 'profile', field.name))
    return 'id', 'email', 'profile'
```

### Use Case
API will work with projects that have email based or phone based authentication

### Database Changes
No Database changes required

**Comment by abhiabhi94** [comment]
Nice observation, this actually opens another issue that I don't think has been considered in the current scenario.

Not all `User` models may use `email` field. As of now, we have assumed the email field to be associated with the `user` account. Any changes there will have issues with the notification system that is being currently built under #43.

**Comment by Radi85** [comment]
hey @ZeroCoolHacker,

Thanks for your suggestion. It seems eligible by me but I would make the field options more generic by introducing a new setting variables with the default user fields:

```python
COMMENT_USER_API_FIELDS = ['id', 'username', 'email', 'profile']
```

and update `get_user_fields`
```python
def get_user_fields(): 
     user_model = get_user_model() 
     fields = user_model._meta.get_fields()
     api_fields = settings.COMMENT_USER_API_FIELDS
     for field in fields: 
         if hasattr(field, "upload_to"): 
             return api_fields.append(field.name)
     return api_fields
```

**Comment by Radi85** [comment]
> Not all `User` models may use `email` field. As of now, we have assumed the email field to be associated with the `user` account. Any changes there will have issues with the notification system that is being currently built under #43.

You are right. But I think this feature should be disabled when the email field is not used in the user model bcz this feature is more likely inteded to be used for those who use the email instead of username.

**Comment by abhiabhi94** [comment]
> You are right. But I think this feature should be disabled when the email field is not used in the user model bcz this feature is more likely inteded to be used for those who use the email instead of username.

I agree that it can/will be disabled. My actual concern is we might have to make the `email` field on the model nullable because as of now it can't be now.

https://github.com/Radi85/Comment/blob/04dfb4f19d824d547bf5b8d33c05076b4469d111/comment/models/comments.py#L16

**Comment by Radi85** [comment]
> This will probably require a lot more changes and a further tryst with the migration test maybe 😨

I don't see any issue here, The email field on comment model was added for allowing anonymous to comment and it's not related to the user model. We need just to update the following method (handle if the email missing from user object) without touching the migration https://github.com/Radi85/Comment/blob/04dfb4f19d824d547bf5b8d33c05076b4469d111/comment/models/comments.py#L70-L72

**Comment by Radi85** [comment]
@ZeroCoolHacker,
Would you like to open a PR for this feature?

**Comment by abhiabhi94** [comment]
> The email field on comment model was added for allowing anonymous to comment and it's not related to the user model. We need just to update the following method (handle if the email missing from user object) without touching the migration 

You are right this was introduced to incorporate anonymous comments. There was also a migration written to fill in the email column for the database to make this change backward compatible.

https://github.com/Radi85/Comment/blob/04dfb4f19d824d547bf5b8d33c05076b4469d111/comment/migrations/0009_auto_20200811_1945.py#L7-L11

This will also need the same exception handling as the one that you mentioned above.

**Comment by ZeroCoolHacker** [comment]
> @ZeroCoolHacker,
> Would you like to open a PR for this feature?

Sure. I'll be happy to
