### ISSUE TITLE
Use pytest-django for testing

### ISSUE THREAD

**Issue by abhiabhi94** [Radi85/Comment#119]
### Change Type
[ ] Refactor/Enhancement
[x] Testing
[ ] CI/CD
[ ] Other

### Proposed Changes
- only tests that need database access can be marked explicitly -> this will help in reducing the time required to run newer tests.(all test cases that import django's `TestCase` are implicitly given the database access.)
- all assertions can be made with the simple `assert` statement without having to remember `assertEqual`. `assertDictEqual` etc
- all existing tests will continue to run, but may be migrated if need arises.
- all other performance improvements of `pytest` can be utilized.
- tests can be run with `pytest` command.

**Comment by Radi85** [comment]
Hey @abhiabhi94,

Can you please fill **Proposed Changes** section?

**Comment by abhiabhi94** [comment]
Other proposed changes is whatever it takes to implement this. There is nothing more that comes to my mind as of now.

Feel free to give any suggestions.

**Comment by abhiabhi94** [comment]
Hey @Radi85, apart from allowing the import lines to be shorter, is there a reason to add the directory `test/example` here:

https://github.com/Radi85/Comment/blob/04dfb4f19d824d547bf5b8d33c05076b4469d111/manage.py#L7-L8

Modifying python-path will require us to use another pytest plugin, This is not a great deal but just wanted to run this through you before adding it.

**Comment by Radi85** [comment]
> Feel free to give any suggestions.

As you previously mentioned, using pytest will enhance the test performance by hitting the DB when only needed. Something like this would be sufficient

**Comment by Radi85** [comment]
> Hey @Radi85, apart from allowing the import lines to be shorter, is there a reason to add the directory `test/example` here:

Yes because `test/example` is not in the current package and it should be add to the path before running the tests.

**Comment by abhiabhi94** [comment]
> Yes because test/example is not in the current package and it should be add to the path before running the tests.

yes, I do understand that. What I meant was:

Currently we do:
```python
from post.models import Post
```

Had we not added this path, we would have to do:
```python
from test.example.post.models import Post
```

**Comment by Radi85** [comment]
I am not sure that would work since `test` package is not yet recognised by the app. You can give it try.

**Comment by abhiabhi94** [comment]
It is recognized. `test` actually happens to me the name of the django project.

https://github.com/Radi85/Comment/blob/04dfb4f19d824d547bf5b8d33c05076b4469d111/manage.py#L6

But as of now, this change will require changes to a lot of places now, specifically for all imports and `apps` module in django. As of now, I'm just ditching in favor of adding a `pytest-pythonpath` plugin.

**Comment by abhiabhi94** [comment]
Should I include #112 in this, as it is I will have to change the tox file for this?

If yes, in place of python3.8, should be just test python3.9 since it is out now?

**Comment by Radi85** [comment]
> Should I include #112 in this? As it is I will have to change the `tox` file for this.
> 
> If yes, in place of python3.8, should be just test python3.9 since it is out now?

Yes for both.
Let's go for python3.6 and 3.9 and django2.1, 3.1 and the master branch.
