### ISSUE TITLE
Cleanup test package

### ISSUE THREAD

**Issue by abhiabhi94** [Radi85/Comment#120]
### Change Type
[ ] Refactor/Enhancement
[x] Testing
[x] CI/CD
[ ] Other

### Proposed Changes

Run `flake8` over complete codebase.

**Comment by Radi85** [comment]
I didn't get what the purpose of this?

**Comment by abhiabhi94** [comment]
There are some unnecessary imports and variables that are lingering inside the test package. Just helps us in cleaning the codebase.

**Comment by Radi85** [comment]
I am not sure that I fully understood but flake8 is already used in the app and I am sure there are no unnecessary imports nor unused variables in the codebase as flake8 is running on the pipline before each test group https://github.com/Radi85/Comment/blob/master/tox.ini#L41

**Comment by abhiabhi94** [comment]
As of now, we run:
```
flake8 comment
```

There is a `test` package(folder that contains `example` app) that where flake8 is not run. I think maybe you are confusing it with the `tests` package inside `comment`.

After proposed changes, we run:
```
flake8
```

**Comment by Radi85** [comment]
I would like to keep it as it is `flake8 /comment` I am not sure why we would care about the other stuff that are outside the app package to be compitable with pep8?!!

**Comment by Radi85** [comment]
By the way `test` package is just a helper project for development purpose and I don't need it to be checked with flake8 or any other code quality tool.

**Comment by abhiabhi94** [comment]
yes, I agree that it is a helper project. I just wanted to run it through `flake8` because it would help in finding out syntactical errors, if made.

Feel free to close the issue in case you think it doesn't hold much value.

**Comment by Radi85** [comment]
In face we don't do much on the `test` project, this can be re-opened in the future if really needed.
