### ISSUE TITLE
Use django built-in EMAIL_FIELD and USERNAME_FIELD

### ISSUE THREAD

**Issue by Radi85** [Radi85/Comment#128]
### Change Type
[x] Refactor/Enhancement
[ ] Testing
[ ] CI/CD
[ ] Other

### Proposed Changes
Replace all occurrences of `user.username` and `user.email` with django built-in fields `USERNAME_FIELD` and `EMAIL_FIELD` respectively.

This will allow us to use the actual `username` and `email` fields on the user model instead of using the default one.

**Comment by abhiabhi94** [comment]
I think we can wait for #126 to merge before we start the work on this. 

Also, just to add a point email might not always be present in the custom user model, so we might need to take that too into account when making this change.
