### ISSUE TITLE
Block user or email from posting and reacting with comments

### ISSUE THREAD

**Issue by Radi85** [Radi85/Comment#143]
### Environment
* django-comments-dab version: 

### Proposed Functionality
The comment's admin or moderator can block a user/email from posting or interacting with comment.

### Use Case
To keep the comment's thread clean from naughty users 😄 and junk emails of anonymous.

### Database Changes

New table: DenyList
```python
class DenyList(models.Model):
    user = models.ForiegnKey(User, null=True, blank=True)
    email = model.EmailField(null=True, blank=True)
    blocker = models.ForiegnKey(User, null=True, blank=True)  # comment moderator
```

**Comment by abhiabhi94** [comment]
`DenyList` or `ExcludeList` as a name for the table would be a more non-racial in my opinion.
