### ISSUE TITLE
Get rid of duplication of code in views and serializers

### ISSUE THREAD

**Issue by abhiabhi94** [Radi85/Comment#144]
### Change Type
[ x] Refactor/Enhancement
[ ] Testing
[ ] CI/CD
[ ] Other

### Proposed Changes

Move logic from `view/serializer` for the sending of emails through services to one of the following:
 
-  register  a custom signal inside `post_save` module maybe. This signal can be connected to a receiver function from the `view/serializer` to handle the logic. 
-  make a utility function to do this. 

The same applies for both sending confirmation for anonymous comment and  notification to followers of a comment. 

Django although recommends using the latter as per our case. To quote:

> When to use custom signals?
Signals are implicit function calls which make debugging harder. If the sender and receiver of your custom signal are both within your project, you’re better off using an explicit function call.

Reference: https://docs.djangoproject.com/en/dev/topics/signals/#defining-and-sending-signals

**Comment by Radi85** [comment]
I am not sure that this refactoring is needed at all. We have discussed this previously in the code review. Email service belongs to the view and moving it a signal doesn't make sense at all and I don't see any duplication that the utility function can solve.

**Comment by abhiabhi94** [comment]
So we have the same logic at three places:

https://github.com/Radi85/Comment/blob/8774a939626f21c853d19a1f95207496084b652b/comment/views/comments.py#L139-L141

https://github.com/Radi85/Comment/blob/8774a939626f21c853d19a1f95207496084b652b/comment/api/views.py#L151-L153

Here the intialization takes place earlier but the duplication is present:

https://github.com/Radi85/Comment/blob/8774a939626f21c853d19a1f95207496084b652b/comment/api/serializers.py#L128-L135

What if we plan to change the signature of the notification function? We would need to change it at three different places.

**Comment by Radi85** [comment]
I agree, in fact there should be a base view class that these views inherit, something like CreateBaseView and implement sending emails in it. I would avoid using utils for refactoring this case.

**Comment by abhiabhi94** [comment]
> in fact there should be a base view class that these views inherit, something like CreateBaseView and implement sending emails in it

A `mixin` is better in my view probably, but a class is an overkill if it has only one method and even that method is a `static` one.

I like the signal option where we register a custom signal `comment_saved_from_request` and connect it to a receiver function `send_notification_to_followers`.

**Comment by Radi85** [comment]
> A `mixin` is better in my view probably, but a class is an overkill if it has only one method and even that method is a `static` one.

`mixin` is a class 😅 so let it be a mixin `CreateCommentMixin`. My idea is to move the comment creation logic to one place and make other views inherit. As I did with toggle follow conecpt.

It's currently pain when we need to change the comment creation flow, it needs to be changed in 2 or three places instead of one. That's the reason behind the duplication.


> I like the signal option where we register a custom signal `comment_saved_from_request` and connect it to a receiver function `send_notification_to_followers`.

I am totaly against signal option.
