### ISSUE TITLE
Update setup documentation. 

### ISSUE THREAD

**Issue by Radi85** [Radi85/Comment#147]
### Change Type
[x] Addition
[ ] Correction
[ ] Deprecation
[ ] Cleanup (formatting, typos, etc.)

### Section
[ ] Installation
[x] Setup
[ ] Usage
[ ] REST API
[ ] Styling
[ ] Settings
[ ] Contribution/Development
[ ] Other

### Proposed Changes

Update instruction for adding `get_absolute_url` method to the model class that uses the comment model.

**Comment by abhiabhi94** [comment]
I think we can add some labels like `good-first-issue` on easier issues like these to maybe encourage more contributions from the community.
