### ISSUE TITLE
Can you make a tutorial on how to build the comments app from scratch?

### ISSUE THREAD

**Issue by tetrahed** [Radi85/Comment#152]
Would it be possible for you to make a tutorial on how you built this library?

**Comment by abhiabhi94** [comment]
I'm afraid I don't complete understand what you mean. 

Do you want a tutorial on how to use this library? If yes, please have a look at the directory https://github.com/Radi85/Comment/tree/develop/test. 
Additional documentation regarding how to use and customize is available at https://django-comment-dab.readthedocs.io/

In case you need more information on how to use `django`, you may look up at https://docs.djangoproject.com

**Comment by abhiabhi94** [comment]
In case you have further questions, we can continue the conversation here. I'm closing this as of now.
