### ISSUE TITLE
Improve the UI for commenting anonymously

### ISSUE THREAD

**Issue by Radi85** [Radi85/Comment#156]
### Environment
* django-comments-dab version:  2.7.0

### Proposed Functionality:

The current UI for commenting anonymously seems to be boring 😒.

I would suggest to use the comment content field only and remove the email field from the view.
When an anonymous user submitting a comment, they should be prompted by a modal form requesting them to provide the email in order to complete the process.

### Use Case
Better and nicer UX/UI

### Database Changes
No

**Comment by abhiabhi94** [comment]
merged in https://github.com/Radi85/Comment/commit/4626539c0ec848d4c79a6efe70bd20f006e9b706
