### ISSUE TITLE
add a rating option for in a situation one wants to rate a model object like in ecommerce website.

### ISSUE THREAD

**Issue by tochimclaren** [Radi85/Comment#160]
### Environment
* Python version: 
* django-comments-dab version: 

### Proposed Functionality
Tis is the best comment app ever on django! what will make it even much better will be to include a rating module with it.

**Comment by Radi85** [comment]
Hey @tochimclaren,

Thanks for the feedback.

Could you please give more details on your feature request? And it would be great to specify the use case.
This feature seems to me to be similar to the reaction that we already have.

**Comment by abhiabhi94** [comment]
closing this, as there has been no updates in a long time.
