### ISSUE TITLE
Any plans for Tailwind CSS support?

### ISSUE THREAD

**Issue by spsphulse** [Radi85/Comment#167]
This is an amazing utility honestly, Do you have any plans of adding tailwind support in the future?

**Comment by Radi85** [comment]
Hey @spsphulse,

Glad to hear your feedback :)

As you already noticed in #15, our plan is to make the app independent from 3rd party libraries.

We have already replaced JQuery by Vanilla JS and our plan is to replace BS by custom style so there is no point of using Tailwind at all.

The milestone for #15 is [3.0.0](https://github.com/Radi85/Comment/milestone/5) but I would move it to [2.7.0](https://github.com/Radi85/Comment/milestone/2)

**Comment by spsphulse** [comment]
Good to know. That makes sense,
