### ISSUE TITLE
link to redirect unauthenticated user for comment, reaction, etc. doesn't work

### ISSUE THREAD

**Issue by mohhammaddaberi** [Radi85/Comment#168]
![Screenshot (42)_LI](https://user-images.githubusercontent.com/61560088/108721323-20455d80-7537-11eb-892c-1260a851a758.jpg)
![Screenshot (44)_LI](https://user-images.githubusercontent.com/61560088/108721707-91851080-7537-11eb-9053-39850e7523b6.jpg)
![Screenshot (46)](https://user-images.githubusercontent.com/61560088/108721995-e163d780-7537-11eb-9191-1d448214bc32.png)

### Environment
* python version 3.8
* django Version 3.1
* django-comments-dab 2.5

### Describe the bug
Note: I uninstalled the app from the packages section and put it in my directory Apps

### Steps To Reproduce
1.
2.
3.

**Comment by Radi85** [comment]
can you please specify the steps to reproduce the bug?

What are the expected and the current behaviors?

**Comment by ZendaInnocent** [comment]
Login link next parameter is set to empty string while it is expected to be the `absolute url` of the model object.

Instead of using `{{ request.path }}`` set to be ``{{ model_object.get_absolute_url }}`` and fixed it for my case.

**Comment by abhiabhi94** [comment]
In this case `request.path` should be the same as `model_object.get_absolute_url`. 

I did some debugging and saw that the actual cause of the problem was that `request` object is not being passed  to the template.

**Comment by mohhammaddaberi** [comment]
Thank you for your emails.I will definitely check.
You are good man.

**Comment by mohhammaddaberi** [comment]
Thank you for your help and assistance. The problem was solved.
