### ISSUE TITLE
Disabled comment form

### ISSUE THREAD

**Issue by spsphulse** [Radi85/Comment#184]
### Environment
* python version 3.9
* django Version 2.2
* django-comments-dab latest

### Describe the bug
The form to add comments does not show up or is disabled. My object detail page has 0 comments. I'm trying to add one, but there is no form for me to enter the comment. 

### Steps To Reproduce
1. All steps followed as per documentation
2. Added the field to my model comments = GenericRelation(Comment)
3. included tempate tag and used render_comments as per documentation.

### Expected behavior
Form to enter comment should ideally show up

### Screenshots

![image](https://user-images.githubusercontent.com/16765855/112712108-4c1b8080-8ef3-11eb-94bd-ca60e0d543fe.png)

![image](https://user-images.githubusercontent.com/16765855/112712135-78370180-8ef3-11eb-9d00-d642dda9de67.png)

**Comment by abhiabhi94** [comment]
Most probably, this seems to be an issue with the theme of your website. If the element appears in the DOM, and isn't hidden by some front end manipulations, it should probably appear.

Could you try and change the `background-color` of the `form` element to see if the element becomes visible?

**Comment by spsphulse** [comment]
My bad! Guess there was some installation issue at my end. 

Removed the app & reinstalled. Everything seems to be working fine. This may be closed.

![image](https://user-images.githubusercontent.com/16765855/112722788-75f39800-8f31-11eb-9e15-4be21037ee27.png)

![image](https://user-images.githubusercontent.com/16765855/112722930-22357e80-8f32-11eb-8bb7-8b6ddf08f009.png)

**Comment by spsphulse** [comment]
Closing my (non)issue.
