### ISSUE TITLE
xss injection

### ISSUE THREAD

**Issue by Alexei055** [Radi85/Comment#210]
### Environment
* python version 3.8.4
* django Version 3.2.2
* django-comments-dab 2.6

### Describe the bug
your form has no protection against xss injections
Sorry in advance, but I checked it out on your live demo
don't worry i deleted my comment

### Steps To Reproduce
1. publish this code in form for comment
<script>alert('Test alert');</script>

### Screenshots
![image](https://user-images.githubusercontent.com/52663858/120431883-c946f400-c381-11eb-9690-1a9339dd26e1.png)

**Comment by abhiabhi94** [comment]
Hey @Alexei055, thanks for the report.

I think the main cause of this is the use of `safe` filters in the template used for rending content here:
https://github.com/Radi85/Comment/blob/0e22c1359257095be2f869838d10d1f3a8d48627/comment/templates/comment/comments/content.html#L7-L13

I think removing these should be sufficient for this. Would you be interested in providing a patch for this?

**Comment by Alexei055** [comment]
Sorry, I cannot make the patch, I will be away from home for about 2 days. I dont have access to working computer
