### ISSUE TITLE
Block function issue on iOS Safari.

### ISSUE THREAD

**Issue by awhileback** [Radi85/Comment#233]
### Environment
* python 3.6
* django 3.2
* django-comments-dab 2.7.0

### Describe the bug
Hello again!  I found another block-related bug.  On iOS (14.7.1, iPhone SE 2020) the block function works, but Safari doesn't allow the method which tries to replace the content of the comment with the reason why the user was blocked.  The error returned is....

```
NoModificationAllowedError: The object can not be modified.
updateBlockedUserComments — comment.js:515
(anonymous function) — comment.js:544
promiseReactionJob


    [Error] NoModificationAllowedError: The object can not be modified. — comment.js:515
	(anonymous function) (comment.js:551)
	promiseReactionJob
```

### Steps To Reproduce
1. open a site on an iPhone (all iPhone browsers are Safari, so all are affected)
2. block a user
3. ....

### Expected behavior

Function return without error. The user is in fact blocked per the database, it appears that this method of replacing the contents of an element don't work on iOS, though.

Unfortunately it seems you need both an iPhone and a MacBook to see this, since iPhones have no debug tools in the browser you have to connect the phone to Safari on a laptop/desktop and then open the phone debugger there.

**Comment by abhiabhi94** [comment]
thanks @awhileback for the report.

i don't have an iphone to test this, is there a way you know i can reproduce this virtually? from the error that you have posted, it seems an element might not be present in the DOM(document object model) probably, and we are trying to modify its property.

does this occur on other browsers as well?

**Comment by awhileback** [comment]
no, just on iOS.

All desktop browsers work fine with the same django installation.
