### ISSUE TITLE
Create Comment with email having field null=true in  user model

### ISSUE THREAD

**Issue by Rohit3412** [Radi85/Comment#240]
create comment required email, and field blank =True but in custom user model what if email field unique =True, null = True 
and blank =True as I go through the comments model where the email field mentioned with Blank = True and it throughs integrity error email can not be null and its avoiding to create a comment.

**Comment by abhiabhi94** [comment]
can you please describe the exact use case, and steps to reproduce the problem? also, it would be great if you can give us the stack trace, this will help in debugging this.

**Comment by Rohit3412** [comment]
step to reproduce :
1. create a user model with email and set email and field unique = True, null = True, blank = True 
example:
`class User(AbstractUser):
    username = models.CharField(unique=True, max_length=120)
    email = models.EmailField(null=True, blank=True, unique=True)`
2. create a user with a null email id but it has a username
3. create a comment on the blog 
it will throws Integrity error 
`django.db.utils.IntegrityError: (1048, "Column 'email' cannot be null")`
it is because in comment model email has been set (blank = True)

**Comment by abhiabhi94** [comment]
Hey @Rohit3412, i'm sorry couldn't respond earlier.

we do set `email` to a blank string if email is not present. 
https://github.com/Radi85/Comment/blob/0e22c1359257095be2f869838d10d1f3a8d48627/comment/models/comments.py#L76-L78

Maybe the unique constraint is a root cause of your problem?
does something like: https://docs.djangoproject.com/en/dev/ref/models/fields/#null helpl?

**Comment by nshaibu** [comment]
Setting uniqueness constraints on a nullable field is not allowed. That is to say, If a field is nullable it can't be unique.

**Comment by abhiabhi94** [comment]
please re-open in case, you still have any related queries.
