### ISSUE TITLE
Show unwanted login message after login with  ?Next parameter in url.

### ISSUE THREAD

**Issue by mohhammaddaberi** [Radi85/Comment#245]
### Environment
* python version 3.9.6
* django Version 3.2.13
* django-comments-dab

### Steps To Reproduce
1.After pressing the Login button in Comment section and then referring to the same post to write a comment,
2.then write first comment and after sending a comment,
3.a message will be displayed that should not be displayed in this place.

### Expected behavior
This message should be displayed on the homepage of the web, or at least after logging in and before posting comments.

### Screenshots
![bug in comment pakage](https://user-images.githubusercontent.com/61560088/174288115-a5c57c22-a534-4789-9ca9-db2cfde84e99.jpg)

**Comment by abhiabhi94** [comment]
closing as per comment: https://github.com/Radi85/Comment/issues/168#issuecomment-1158631242.
