### ISSUE TITLE
button "read more" doesn't work correctly

### ISSUE THREAD

**Issue by ogurec-ogurec** [Radi85/Comment#269]
If in the comment field we copy structured text, for example:

```
Where does it come from?
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham. 
```
when publishing a "read more" button appears, 

![image](https://github.com/Radi85/Comment/assets/66796268/f1353786-2b11-406c-b6c5-259a4bf9fd51)

but if we publish, for example, the following text:

`dasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdasdasdsasssssssssssssssssssssssssssdas`

then the **read more button does not appear**:

![image](https://github.com/Radi85/Comment/assets/66796268/0de1aaeb-fe9e-47e9-be04-dafe75b17b5d)

example: https://rmustafa.pythonanywhere.com/test-post/?

Does anyone have any thoughts on this matter?

**Comment by ChathuraGH** [comment]
Hello friend 🖐. I   have an answer.

1. go to "site-packages\comment\templatetags\comment_tags.py"
(source of comments app)
2. make a copy of this file to a safe location as backup(just in cause)
3. replace `def render_content(content, number):` function with below code.

```
#by @ChathuraGH
def render_content(content, number):
    number = int(number)#by @ChathuraGH
    max_length = (number*5)+number#by @ChathuraGH
    if not number or ((len(content) <= max_length) ):#by @ChathuraGH
        text_1 = content
        text_2 = None
    elif( (len(content) > max_length) ):#by @ChathuraGH
        text_1 = content[:max_length]#by @ChathuraGH
        text_2 = content[max_length:]#by @ChathuraGH
    return {
        'text_1': text_1,
        'text_2': text_2
    }
```

4. go to "site-packages\comment\templates\comment\comments\content.html"

5. replace the content of this file with below code.

```
<p class="js-comment-content {% block c_text_cls %}mb-0{% endblock c_text_cls %}">
    {% if text_2 %}
        {{ text_1 }}<span class="d-none">{{ text_2 }}</span>
        <button class="js-read-more-btn btn btn-link btn-xs" style="font-size: 14px">read more...</button>
    {% else %}
        {{ text_1 }}
    {% endif %}
</p>
```

**Happy coding 😲**

**Comment by ogurec-ogurec** [comment]
@ChathuraGH Hello, thanks for the advice. The code worked, but it seemed to me that it was not worth replacing the entire `render_content` function, but that you could simply add a limit condition (max_lehght), since in addition to restrictions on the output of word-characters, the `render_content` function has security against XSS attacks (`mark_safe()`). "read more" :)
![image](https://github.com/Radi85/Comment/assets/66796268/26c3124a-0465-4586-88c9-17cf65e8c29f)

**Comment by ChathuraGH** [comment]
Ok. Cool. 👌. My testing version doesn't have `make_safe()`. That's why answer didn't include that. It was nice to help you.
