### ISSUE TITLE
can not install successfully with python 3.7.3

### ISSUE THREAD

**Issue by huchunnuan** [Radi85/Comment#3]
when I  run "pip install django-comments-dab"
ERROR: Command "python setup.py egg_info" failed with error code 1

**Comment by Radi85** [comment]
The issue is not related to `django-comments-dab` but to your python environment. However I already installed the package successfully in python3.7.3 environment.

make sure your `setuptools` is up to date:
`pip install --upgrade setuptools`

**Comment by STRIX84** [comment]
I’ve error NoneType .
I would add this comments system in my project but
Not work. 
Help me pls.

**Comment by Radi85** [comment]
Please open another issue and post your traceback.
I will keep this close since it's related to different issue.
