### ISSUE TITLE
Problems with reaction icons

### ISSUE THREAD

**Issue by emac62** [Radi85/Comment#34]
hey there,

I have a couple of issues.

The like/dislike icons work as expected with the 'thumbs' icon. If I change them, following the instructions at readthedocs, the toggling goes away. I have to reload the page to update the number. 

The flag link does not work at all. (I only allow comments for authenticated users.)

Also, I cannot delete a comment. Here is the console.
![Screen Shot 2020-06-20 at 4 09 39 PM](https://user-images.githubusercontent.com/13800336/85332237-94f66280-b4a5-11ea-9f66-053136cc33fe.png)

Thank you for the recent updates.

**Comment by Radi85** [comment]
hey @emac62,

Fisrt of all I would recommend to update your current version.

> The like/dislike icons work as expected with the 'thumbs' icon. If I change them, following the instructions at readthedocs, the toggling goes away. I have to reload the page to update the number.

You are righ. The issue here comes from missing classes `comment-reaction-icon reaction-like`, add these class to your new icon. I will update the docs with the new release.
```jinja
{% extends 'comment/reactions/like_icon.html' %}

{% block like_img_icon %}
    <div class="comment-reaction-icon reaction-like">icon</div>
{% endblock %}
```

> The flag link does not work at all. (I only allow comments for authenticated users.)
> Also, I cannot delete a comment. Here is the console.

I could not find any issue here, so as I said is the best to upgrade your version to the latest.

looking for your feedback.

**Comment by emac62** [comment]
Thank you for such a quick reply. I have upgraded to 1.6.5.5, retraced my steps and still have the some problems. 

This is what I'm working with:

macOS 10.13.6

Django==3.0.7
django-bootstrap4==2.2.1
django-bootstrap-form==3.4
djangorestframework==3.11.0

bootstrap cdn is 4.1.1
jquery-3.3.1.js

in settings.py: `COMMENT_FLAGS_ALLOWED=1`

Here is the like_icon.html file in my templates folder:
`{% extends "comment/reactions/like_icon.html" %}

{% block like_img_icon %}<div class="comment-reaction-icon reaction-like"><i
    class="far fa-heart"></i>{% endblock like_img_icon %}</div>
{% block like_icon_color %}#E99701{% endblock like_icon_color %}`

Here's the result:
![Screen Shot 2020-06-23 at 2 33 02 PM](https://user-images.githubusercontent.com/13800336/85483195-61ddcd00-b592-11ea-83e0-003e6b1762ef.png)

The delete button and the Flag button do not open the modals (but the tooltip comes up). The error message in the console is still the same.

What am I missing? Thank you so much for your help.

**Comment by Radi85** [comment]
I believe the issue is because of missing element classes, as I mentioned prevoiusly `class="comment-reaction-icon reaction-like"` these classes must be added to the new icon element.

However, I have overrided the defalut icons as below and all functionality kept working as expected.

<img width="940" alt="Screenshot 2020-06-24 at 12 36 07" src="https://user-images.githubusercontent.com/25413382/85540975-df97ec00-b617-11ea-92d3-308a4823d661.png">

**like icon**

```jinja
{% extends 'comment/reactions/like_icon.html' %}

{% block like_img_icon %}
{% load comment_tags %}
{% has_reacted user=user comment=comment reaction="like" as has_user_liked %}
<svg xmlns="http://www.w3.org/2000/svg"
 width="18" height="18" viewBox="-10 -28 550 500"
 xml:space="preserve"
     stroke="#427297"
     stroke-width="20"
    class="comment-reaction-icon reaction-like {% if has_user_liked %}user-has-reacted{% else %}user-has-not-reacted{% endif %}">
    <path d="m471.382812 44.578125c-26.503906-28.746094-62.871093-44.578125-102.410156-44.578125-29.554687 0-56.621094 9.34375-80.449218 27.769531-12.023438 9.300781-22.917969 20.679688-32.523438 33.960938-9.601562-13.277344-20.5-24.660157-32.527344-33.960938-23.824218-18.425781-50.890625-27.769531-80.445312-27.769531-39.539063 0-75.910156 15.832031-102.414063 44.578125-26.1875 28.410156-40.613281 67.222656-40.613281 109.292969 0 43.300781 16.136719 82.9375 50.78125 124.742187 30.992188 37.394531 75.535156 75.355469 127.117188 119.3125 17.613281 15.011719 37.578124 32.027344 58.308593 50.152344 5.476563 4.796875 12.503907 7.4375 19.792969 7.4375 7.285156 0 14.316406-2.640625 19.785156-7.429687 20.730469-18.128907 40.707032-35.152344 58.328125-50.171876 51.574219-43.949218 96.117188-81.90625 127.109375-119.304687 34.644532-41.800781 50.777344-81.4375 50.777344-124.742187 0-42.066407-14.425781-80.878907-40.617188-109.289063zm0 0"></path>
</svg>

{% endblock %}
```

**dislike icon**

```jinja
{% extends 'comment/reactions/dislike_icon.html' %}

{% block dislike_img_icon %}
{% load comment_tags %}
{% has_reacted user=user comment=comment reaction="dislike" as has_user_disliked %}
<svg xmlns="http://www.w3.org/2000/svg"
 width="18" height="18" viewBox="0 0 992.182 992.181"
 xml:space="preserve"
     stroke="#427297"
     stroke-width="40"
    class="comment-reaction-icon reaction-dislike {% if has_user_disliked %}user-has-reacted{% else %}user-has-not-reacted{% endif %}">
    <g>
	<path d="M749.204,93.337c-82.4,0-155.601,40-200.101,101.5c-9.699,13.5-11,31.4-3.5,46.2l20.4,40.6c7,14,6.3,30.6-2,43.9
		l-42.6,68.6c-9.101,14.601-9,33,0.1,47.601l41.5,66.399c8.9,14.2,9.1,32.101,0.7,46.601l-43.7,74.6c-8.2,14-8.2,31.4,0,45.5
		l44.8,76.601c7.8,13.399,8.2,29.899,1,43.6l-51.8,99c14.4,7.3,31.8,6.3,45.4-3.1c42.399-29.5,133.199-92.9,133.199-92.9
		c76.7-54.9,149.9-114.9,207-190.7c49.101-65.2,85-142.399,91.601-223.8C1003.004,235.538,907.104,93.337,749.204,93.337z"></path>
	<path d="M300.303,797.938c0,0,91.4,63.5,134.101,93c1.699,1.1,3.399,2.199,5.1,3.1l51.8-99c7.201-13.7,6.8-30.2-1-43.6
		l-44.8-76.601c-8.2-14-8.2-31.399,0-45.5l43.7-74.6c8.5-14.4,8.2-32.4-0.7-46.601l-41.5-66.399c-9.1-14.601-9.1-33-0.1-47.601
		l42.6-68.6c8.3-13.3,9-29.9,2-43.9c-20.7-41.2-39.1-82.4-72.1-115.4c-28.801-28.8-64.601-50.3-103.5-62.2
		c-23.5-7.1-48-10.7-72.601-10.7c-157.8,0-254.3,142.2-242.3,290.1c6.6,81.399,42.2,158.6,91.3,223.8
		C149.503,683.137,223.604,743.137,300.303,797.938z"></path>
     </g>
</svg>

{% endblock %}
```

**Comment by emac62** [comment]
That worked! Thank you! 

I figured out the delete and flag modals too! I had jquery loaded twice. Everything works as it should now. Thank you again!

**Comment by Radi85** [comment]
Cool. You are welcome and thanks for the feedback.
