### ISSUE TITLE
Add permalink to each comment

### ISSUE THREAD

**Issue by abhiabhi94** [Radi85/Comment#36]
_Originally posted by @abhiabhi94 in https://github.com/Radi85/Comment/issues/33#issuecomment-648842742_

**Comment by abhiabhi94** [comment]
Hey Radi, I see that you have moved the flag icon to the right. Now where should this permalink option go?

- One of the possible places could be just beside the right of the title of the comment. I must not sure this will make the design look clean.

- Another option would be make a three dot kebab icon similar to something that github gives with comments. This kebab could be used for edit, delete, copy link and flag option.

**Comment by Radi85** [comment]
What about putting it next to the reaction icons with float right?

**Comment by abhiabhi94** [comment]
In my opinion it would make th design look a bit scattered.

**Comment by abhiabhi94** [comment]
or we can use the symbol ¶ just beside the comment title. We may also activate that element only when the hover event is activated over the comment title element. This is similar to what we see in the official django documentation.

Although to someone like me,  it would feel like obfuscating the feature.
