### ISSUE TITLE
'RelatedManager' object has no attribute 'all_comments_by_object'

### ISSUE THREAD

**Issue by dataspider99** [Radi85/Comment#39]
Request Method: | GET
-- | --
http://localhost:8000/team/detail/1
2.1.5
AttributeError
'RelatedManager' object has no attribute 'all_comments_by_object'
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/comment/templatetags/comment_tags.py in get_comments_count, line 52
/usr/local/bin/python3.6
3.6.8

**Comment by Radi85** [comment]
`all_comments_by_object` method is already implemented in CommentManager. I am not sure where the error come from but I think it may be not the right object passed to `{% render_comment %}` tag as described [Here](https://github.com/Radi85/Comment#1-basics-usage)

**Comment by dataspider99** [comment]
I had another model with same name that's why it was not working.
