### ISSUE TITLE
Signals

### ISSUE THREAD

**Issue by emac62** [Radi85/Comment#68]
I would like to create a post_save signal to use to notify the author of the post that someone has commented. I can't seem to get the post.id associated with the comment. This is the only code I've tried that gives me something:

`@receiver(post_save, sender=Comment)
def comment_saved(sender, **kwargs):
   obj = kwargs
   print(obj)`

And this is what is printed:
`'instance': comment by fergitwinsmom: Nice pics, 'created': True, 'update_fields': None, 'raw': False, 'using': 'default'`
This gives me the user who made the comment but not the post that the comment belongs to so I can get the author of the post.

Is there a way to get the post.id?

**Comment by abhiabhi94** [comment]
`instance.object_id` is your model id.


In case you have comment associated with more than one model:
```python

model_id = instance.object_id
app_name = instance.content_type.app_label
model_name = instance.content_type.model

from comment.utils import get_model_obj

model_obj = get_model_obj(app_name, model_name, model_id)
```

**Comment by emac62** [comment]
Thank you so much! It worked!
