### ISSUE TITLE
Rating System

### ISSUE THREAD

**Issue by avlord** [Radi85/Comment#7]
Hello! Thx y for your awesome app. Is it possible to add Rating System (Like/ Dislike for comment, like on Reddit)? 
Or maybe you will give some idea how to properly implement it.

**Comment by Radi85** [comment]
Hey @avlord, thanks for the feedback. I was thining about adding this feature and it will be added soon. Any ideas or contribution will be most welcome!

**Comment by Radi85** [comment]
This will be closed since it's covered in #8
