### ISSUE TITLE
Add translational capabilities to the application.

### ISSUE THREAD

**Issue by abhiabhi94** [Radi85/Comment#70]
I think we should open a new issue to integrate translations and with this we can cover everything. And we might start adding the translation files for some languages.

_Originally posted by @Radi85 in https://github.com/Radi85/Comment/pull/67#discussion_r487401673_

**Comment by abhiabhi94** [comment]
Parts to be covered

[ ] Add translational capabilities to backend responses.
[ ] Add translational capabilities to template strings.
[ ] Add translational capabilities to javascript responses.

I think the addition of translational files for different languages can be moved to a separate issue.

This can be assigned to me.

**Comment by Radi85** [comment]
> I think the addition of translational files for different languages can be moved to a separate issue.

I agree.
