### ISSUE TITLE
Style customization 

### ISSUE THREAD

**Issue by ChathuraGH** [Radi85/Comment#73]
Thanks for continuing development guys.
**1#**    When i put load comments in <div> it wrap words as expected, but it doesn't break long words. So I used css break-all, now all lines make one paragraph.I want to use as text in <div > with word-wrap :break-word. 

**2#**  when typing long comments comment posting button stays at top. Can its position at bottom of text area. Or make it customisable.

**Comment by abhiabhi94** [comment]
> Thanks for continuing development guys.

You are welcome. Just to point it out, contrary to popular perception, guys is not a gender-neutral term. You may use something like folks, everyone etc. Please visit https://heyguys.cc for reference.

 > it wrap words as expected, but it doesn't break long words. So I used css break-all, now all lines make one paragraph.I want to use as text in
with word-wrap :break-word.

I think we could get a better idea about your problem if you could supplement it with screenshots.

> when typing long comments comment posting button stays at top. Can its position at bottom of text area. Or make it customisable.

this seems an interesting problem to look upon. Perhaps @Radi85 would be able to share more light upon some possible workarounds.

**Comment by ChathuraGH** [comment]
Ok.I just changed comment button style to position :sticky and top:70% by overriding template and button position work fine now.
I think it's ok to add that style to app also.

**Comment by ChathuraGH** [comment]
For word wrapping I added word-wrap :break-all;white-space :pre-line; by overriding default comment.css now work fine. If you think it is useful add it to app. Goodbye.
