### ISSUE TITLE
POST request for create-comment goes to the wrong URL

### ISSUE THREAD

**Issue by shishirdash** [Radi85/Comment#76]
**Environment**
* python version 3.7
* django Version 3.0.5
* django-comments-dab 2.0.0

**Describe the bug**
I'm trying to integrate the `comment` app into a Community app in a manner similar to the example Post app. Our webapp is called `communities` and the relevant model in which we want commenting enabled (equivalent to `Post` in the example) is called `Thread`.  Followed all the steps as required in the readme and made sure to run tests. 

However, when I try to submit a comment, the POST request is sent to the wrong url. I've double checked all the patterns and have reported my settings and template stubs below. 

I suspect there is some more nuance to setting the url patterns than what is described in the readme, and any help would be appreciated.

**Reproducing the bug**
When I start the server and navigate to the thread detail page, the comment form is rendered correctly....
![image](https://user-images.githubusercontent.com/8041474/93276730-40e1de00-f775-11ea-8efb-0c37dea26c18.png)

However, when I type in an example comment and hit the submit button, nothing happens. When I inspect the terminal output, I can see that its actually sending the POST request back to the `thread_detail` view instead of the `CreateComment` 
view. Here's a screenshot of the terminal output:
![image](https://user-images.githubusercontent.com/8041474/93277057-265c3480-f776-11ea-9b88-0e1d678f848f.png)

For your reference, here is the `urls` file, the relevant model for `Thread` and the relevant `thread_detail` template.

`urls.py` in the top level webapp:
```
...
path('<slug:community_name_slug>/<slug:category_slug>/threads/<int:thread_pk>/',
         view=login_required(thread_views.thread_and_comment_view),
         name='thread_detail'),
path('<slug:community_name_slug>/<slug:category_slug>/threads/<int:thread_pk>/like/',
         view=login_required(thread_views.like_thread_view),
         name='thread_like'),
    path('<slug:community_name_slug>/<slug:category_slug>/threads/<int:thread_pk>/pin/',
         view=login_required(thread_views.pin_and_unpin_thread),
         name='thread_pin'),
    path('<slug:community_name_slug>/<slug:category_slug>/threads/<int:thread_pk>/edit/',
         view=login_required(thread_views.update_thread),
         name='thread_edit'),
    path('<slug:community_name_slug>/<slug:category_slug>/threads/<int:thread_pk>/delete/',
         view=login_required(thread_views.ThreadDeleteView.as_view()),
         name='thread_delete'),

    path('comment/', include('comment.urls')),
    path('api/', include('comment.api.urls')),
...
```

Model `Thread`:
```
class Thread(models.Model):
    title = models.CharField(max_length=140) # Thread title
    message = models.TextField(max_length=4000, blank=True, null=True)  # Thread body
    type = models.CharField(max_length=2, choices=THREAD_TYPE_CHOICES, default=POST)
    created_at = models.DateTimeField(auto_now_add=True)  # Timestamp of last updation
    ...
    comments = GenericRelation(Comment)
```

Template `thread_detail.html`:
![image](https://user-images.githubusercontent.com/8041474/93276633-f06a8080-f774-11ea-8b15-a429324a155e.png)

**Comment by abhiabhi94** [comment]
> I suspect there is some more nuance to setting the url patterns than what is described in the readme

No, it wasn't suppose to be meant that way ;)

Interesting....

From what I can see, you have a `form`  in your template `thread_detail.html` whose submission is supposed to the URL pointed by `thread_like`.  I'm not sure where the URL pointed by `thread_detail` is coming from.

Could you please check if that form is getting submitted by somehow? You can use the developer console inside your browser to see the network requests sent and see the script triggering it.

**Comment by shishirdash** [comment]
@abhiabhi94   -- I'm not sure I understand your question. Guessing you're trying to understand which url the `submit` button leads to?

My intention when I hit the `Comment` button is to render the view `thread_detail` again with the new comment correctly rendered. The corresponding view is:
```
def thread_and_comment_view(request, community_name_slug, category_slug, thread_pk, comment_pk=None):
    community = get_object_or_404(Community, slug=community_name_slug)
    user_communities = Community.active.filter(users=request.user)
    category = community.thread_categories.get(slug=category_slug)
    filter_criteria = request.GET.get('filter')
    pinned_thread = get_pinned_thread(community, category_slug=category_slug)

    if not filter_criteria:
        filter_criteria = 'created_at'

    community_threads = order_threads(filter_threads(
        community, category, category_slug
        ), order_criteria=filter_criteria)

    thread = get_object_or_404(Thread, community__pk=community.pk, pk=thread_pk)
    liked = False
    if thread.likes.filter(id=community.organization_users.get(user=request.user).id).exists():
        liked = True

    session_key = 'viewed_thread{}'.format(thread.pk)
    if not request.session.get(session_key, False):
        thread.views += 1
        thread.save()
        request.session[session_key] = True

    context_dict = {
        'community': community, 'community_threads': community_threads,
        'thread': thread, 'total_likes': thread.total_likes(), 'liked': liked,
        'category': category, 'filter': filter_criteria, 'all_of_user_communities': user_communities,
        'is_admin': community.is_admin(request.user), 'pinned_thread': pinned_thread,
    }

    return render(request, 'communities/thread_detail.html', context=context_dict)
```

As you can see, I've not added any logic around comments in this view method. I wanted to keep it exactly the same flow as in the example `post/views.py`, which does not contain any explicit call to the `Comment` model either:
```
...
class PostListView(ListView):
    model = Post
    template_name = 'post/postlist.html'
    paginate_by = 10


class PostDetailView(DetailView):
    model = Post
    template_name = 'post/postdetail.html'

....

```

Lmk if my approach is not clear?

**Comment by abhiabhi94** [comment]
The picture of your developer console shows a request is made to the URL `communities/hawaii/all/threads/1/?filter=created_at` which is pointed by the URL name `thread_detail`.

The picture of your template `thread_detail.html` shows there is a form that gets submitted to the URL pointed out by the name `thread_like`.

There is network tab inside the developer console of your browser that monitors all the requests. Could you just use it to look what script is causing the trigger to make a request to `communities/hawaii/all/threads/1/?filter=created_at`? 

Network tab/monitor for reference: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

It would be great if you could paste the rendered HTML content inside the browser for the `comment` element too. 
Hint: It would be inside something like this:
```html
<section id="comments" class="my-5 mx-3">
....
</section>
``` 

Also consider pasting the code rather than a picture. It is generally easier to point out the part by just copying and pasting.

**Comment by Radi85** [comment]
@shishirdash 
> However, when I try to submit a comment, the POST request is sent to the wrong url. I've double checked all the patterns and have reported my settings and template stubs below.

Posting a comment should not interact with your urls and JS fetch library is used to perform the http requests. Therefore, I think maybe some html classes were changed when you costumized the comment button.

**Comment by abhiabhi94** [comment]
@Radi85 I think we can improve the documentation regarding customization, which classes to keep specifically when doing this. If i am not wrong, this was an issue with one of the earlier users as well when changing icons for reactions.

**Comment by shishirdash** [comment]
Thanks @abhiabhi94  and @Radi85  for the replies. 

@abhiabhi94 -- here's the rendered HTML content for the comments section:
```

<section id="comments" class="my-5 mx-3">
--
 <script>window.CSRF_TOKEN = "QxXQKBewKRyypuAxt9HMoBsvhbgEwbJBH5ivGedfpte3798w2LzIbC5FXnXliSvT"</script>
 <strong class="border-bottom bb"><span class="js-comment-number">0</span> Comments</strong>
 
 
 <hr class="hr"/>
 <div class="js-comment comment mb-5">
  
 <form class="js-comment-form" method="post" data-url="/communities/comment/create/">
 <input type="hidden" name="csrfmiddlewaretoken" value="QxXQKBewKRyypuAxt9HMoBsvhbgEwbJBH5ivGedfpte3798w2LzIbC5FXnXliSvT">
 <div class="row">
 <div class="col-sm-9 col-md-10 px-2 m-2 m-sm-0">
 
 
 <textarea name="content" cols="40" rows="1" placeholder="comment on this post ..." class="js-comment-input form-control form-control-sm rounded-0" required id="id_content">
 </textarea>

 
 </div>
 <input name="model_name" value="Thread" hidden>
 <input name="model_id" value="2" hidden>
 <input name="app_name" value="communities" hidden>
 <input name="oauth" value="True" hidden>
 
 <div class="col-sm-3 col-md-2 px-2 m-3 m-sm-0">
 <button class="js-comment-btn
 btn btn-primary btn-block btn-sm
 "
 type="submit" name="form_type" value="parent">
 Comment
 </button>
 </div>
 </div>
 </form>
 

 </div>
 <div class="js-main-comment mt-5">
 
 </div>
 
 <div class="comment-modal" id="Modal">
 <div class="comment-modal-dialog" role="document">
 <div class="comment-modal-content">
 </div>
 </div>
 </div>
 
 
 </section>

```

**Comment by shishirdash** [comment]
I looked into the various requests to the thread URL. I'm attaching a screenshot of what I see on the Network tab in Devtools, and filtering for rhe `all/threads` pattern.  (Created a new thread with base url: `communities/yellowstone/3` just to keep things clean)

![image](https://user-images.githubusercontent.com/8041474/93637288-33616980-f9aa-11ea-82fb-040c7e0f59c3.png)

My user actions to generate this sequence were:
First: load thread home page
Then, row 2 (& 3): Like the thread (this sends a redirect request to the `/all/threads/3` page
Final row. Type some thing in the comments form and hit "Comment" button

As you can see, the Initiator tab just says "Other" for these above requests. 

When I see the list of all requests preceding the "Comment" action, I see the following (the POST request is the relevant "Comment" action): 
![image](https://user-images.githubusercontent.com/8041474/93638092-8c7dcd00-f9ab-11ea-859e-e637b9c8ea32.png)

PS: Did my best to capture output faithfully. I couldn't find a way to capture it easily in text, so using screenshots for now :-/

**Comment by Radi85** [comment]
I believe the issue is now obvious. The data-url attribute in the form points to a wrong url `data-url="/communities/comment/create/">` this in fact must be `data-url="/comment/create/">` so I think you are nesting the comment urls inside `communities` urls. If this the case, please move comment urls to the root urls and give it try.

**Comment by shishirdash** [comment]
Thanks @Radi85 -- you were correct that the comments urls were being nested inside community. However, even after moving it to the  root `urls.py` (i.e., inside `config.urls`), I see the same issue. That is, when I type in a comment in the form and hit "Comment" it refreshes the thread view but does not render the comment.

Here is how my `config.urls` file looks like now after I added the `comment/` and `api/` paths:
```
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from communities.backends import invitation_backend, registration_backend

urlpatterns = [
    path('forum-hq-admin-page/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('users.urls')),
    path('communities/', include('communities.urls')),
    path('invite/', include(invitation_backend().get_urls())),
    path("register/", include(registration_backend().get_urls())),
    path('', include('pages.urls')),
    path('activity/', include('actstream.urls')),
    path('comment/', include('comment.urls')),
    path('api/', include('comment.api.urls')),  # only required for API Framework
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

```

And for your reference, here is the page source for the rendered thread page. You'll notice that the `data-url` variable is now being set correctly to `"/comment/create/"`, just as 
```
<section id="comments" class="my-5 mx-3">
    <script>window.CSRF_TOKEN = "HbHJwNYhM9dRtc6hrx148xSmNIcPLAIGyJ2osqX0rLTmbREg09T0VyvwtUTwxhuY"</script>
    <strong class="border-bottom bb"><span class="js-comment-number">0</span> Comments</strong>
    
   
    <hr class="hr"/>
    <div class="js-comment comment mb-5">
        
    <form class="js-comment-form" method="post" data-url="/comment/create/">
        <input type="hidden" name="csrfmiddlewaretoken" value="HbHJwNYhM9dRtc6hrx148xSmNIcPLAIGyJ2osqX0rLTmbREg09T0VyvwtUTwxhuY">
        <div class="row">
            <div class="col-sm-9 col-md-10 px-2 m-2 m-sm-0">
                   
    <textarea name="content" cols="40" rows="1" placeholder="comment on this post ..." class="js-comment-input form-control form-control-sm rounded-0" required id="id_content">
</textarea>
    
            </div>
            <input name="model_name" value="Thread" hidden>
            <input name="model_id" value="3" hidden>
            <input name="app_name" value="communities" hidden>
            <input name="oauth" value="True" hidden>
            
            <div class="col-sm-3 col-md-2 px-2 m-3 m-sm-0">
                <button class="js-comment-btn 
btn btn-primary btn-block btn-sm
"
                        type="submit" name="form_type" value="parent">
                    Comment
                </button>
            </div>
        </div>
    </form>

    </div>
    <div class="js-main-comment mt-5">
      
    </div>

    <div class="comment-modal" id="Modal">
      <div class="comment-modal-dialog" role="document">
        <div class="comment-modal-content">
        </div>
      </div>
    </div>

</section>
```

**Comment by abhiabhi94** [comment]
> That is, when I type in a comment in the form and hit "Comment" it refreshes the thread view but does not render the comment.

What happens?

**Comment by shishirdash** [comment]
It just refreshes the same page. Without actually rendering the comment.

**Comment by abhiabhi94** [comment]
What request do you see on the developer console? Does it show any error?

Also, did you use the `include_static` in the template used for rendering comments? it is used to load the CSS and javascript files.

**Comment by shishirdash** [comment]
Ah -- thank you so much!! it was precisely including the `include_static` tag in the `thread_detail.html` that fixed this! Here's a screenshot of the resulting page (will now focus on getting rid of the authentication message)

![image](https://user-images.githubusercontent.com/8041474/93689414-2e241d80-fa83-11ea-9750-c0ac3bf404dc.png)

In hindsight this seems obvious 🤦 :-) ... but I was mistakenly thinking that `{% render_comments thread request oauth %}` was already doing that. 

Appreciate the help!

**Comment by Radi85** [comment]
> In hindsight this seems obvious 🤦 :-) ... but I was mistakenly thinking that `{% render_comments thread request oauth %}` was already doing that under the hood.
> 

Glad to see that the issue is solved. It's a good point and we may consider rendering the static files in the `render_comments` tag.

**Comment by abhiabhi94** [comment]
Hey @Radi85, this makes sense to me. The `css` and `js` files always need to be included for templates, so we may rather place them directly inside the `base.html` template.

If you agree to this, I will make the pull request for this.

**Comment by Radi85** [comment]
> Hey @Radi85, this makes sense to me. The `css` and `js` files always need to be included for templates, so we may rather place them directly inside the `base.html` template.
> 
> If you agree to this, I will make the pull request for this.

I do agree. I already started with this.
