### ISSUE TITLE
Integrate user profile not working if variable different in profile model

### ISSUE THREAD

**Issue by learnICT** [Radi85/Comment#79]
**Environment**
* python version 3.8
* django Version 3.1.1
* django-comments-dab 2.0

**Describe the bug**
I have added the profile_app_name and profile_model_name to the `settings.py`:

```
PROFILE_APP_NAME = 'hesaplar'
PROFILE_MODEL_NAME = 'Kullanici' # letter case insensitive

```
The error says, 
`Cannot resolve keyword 'user' into field. Choices are: dogum, ensicak, id, insta, kullanici, kullanici_id, paylasimlar, resim, sehir, takipciler, yorumlar`

I am assuming this is because, in my profile app, I am not using `user` as the variable name for the user but instead `kullanici `(The Turkish equivalent).

My user model looks likes this:

```
class Kullanici(models.Model):
    kullanici = models.OneToOneField(User, on_delete=models.CASCADE)
    ...
```

Any ideas how I can overcome this?

**Comment by abhiabhi94** [comment]
Currently, for your case you may add a property inside your `Kullanici` model:

```python

class Kullanici(models.Model):
       ...
    @property
     def user(self):
         return self.kullanici
```

I know this is not the most elegant solution but should do the work for you. Thanks for pointing out the bug, we will try to find out a better solution to handle this case.

**Comment by learnICT** [comment]
> Currently, for your case you may add a property inside your Kullanici model:
> class Kullanici(models.Model):
>        ...
>     @property
>     def user(self):
>         return self.kullanici
> I know this is not the most elegant solution but should do the work for you. Thanks for pointing out the bug, we will try to find out a better solution to handle this case.

Thank you, I will try this tonight!
