### ISSUE TITLE
Add Reactions

### ISSUE THREAD

**Issue by abhiabhi94** [Radi85/Comment#8]
This is similar to #7 

Add reactions of the type:
- like
- dislike
- flag/report

To add these things, I think we would need an abstract model to extend them(reactions) as property. Any other ideas would be great.

Before adding these fields, we need to answer a couple of questions:
- Would we want these reactions to be used only if a user decides to use them? Preferably a configuration in the settings file, that allows them to add these fields.
- What could be the potential reasons for flagging/reporting?
- How would the flagging process work? 
     - I had made an application for flagging which is somewhat usable right now. Would the process be similar to this one? 
![here](https://raw.githubusercontent.com/abhiabhi94/idea-fare/master/flag/images/flagging.gif)

I would be willing to put together a pull request if we can decide about the details regarding the implementation.

**Comment by Radi85** [comment]
Hey @abhiabhi94,
I would like to adapt your suggestion as follows:
* It's preferably to let the user choose whether using these reactions or not. Adding this config to setting as suggested is great and I would prefer to split *like/dislike* and *flag/report* settings.
* Report reasons *spam* and *abuse* as shown in your image are sufficient for now.
* Please use the same flag process in your app.

PS: All post requests shall be handeled through AJAX and please consider adding sufficient unittests.

Looking forward to your PR.

**Comment by abhiabhi94** [comment]
- Do we want the flagging and other reactions to be a part of the same application or plan to keep them separate?
    - Do we call the separate models as `reaction` and `flag`?

- Regarding the third reason shown in the image that says `something else`, there would be a comment box that would open. The form would only submit only if user entered some values inside the comment box. This is generally for all sorts of different reasons like fake content/news, hurtful content like bigotry, etc, or something else that we couldn't think about. Do we still want to keep the first two reasons?
    - We can also let the user decide the reasons for flagging through a configuration inside the settings file and just place these two/three reasons as default.

For what it's worth, I made a pluggable flag application and its code is hosted [here](https://github.com/abhiabhi94/idea-fare/tree/master/flag). I haven't written any documentation or tests as of now but the code seems usable to me. You may review it and tell me if there's something good that we can use from there. It currently uses `POST` requests.

**Comment by Radi85** [comment]
* I would like to have them integrated in our app, feel free to name the models as you like.
* I like the idea to make the flags options configurable in the settings where the user can use his own flags and `something else` must be always there.

I will have a look at your app.

**Comment by abhiabhi94** [comment]
>     * I would like to have them integrated in our app, feel free to name the models as you like

Do we need to put both the models inside one application `reaction` or put `flag` model in a separate application `flag`?

**Comment by Radi85** [comment]
I would prefer to stick with one app and no external dependencies, this is my goal in the last update.
For our case, we might use the following structure
```
.
└── comment
    ├── models
    │   ├── __init__.py
    │   ├── comments.py
    │   ├── flags.py
    │   └── reactions.py
    └── views
        ├── __init__.py
        ├── comments.py
        ├── flags.py
        └── reactions.py
```

**Comment by Radi85** [comment]
I had a look at the [models](https://github.com/abhiabhi94/idea-fare/blob/master/flag/models.py) in your flag app, great work :) .
For our app and since the `flag` system will be created for the `comment` model only, I would use it directly insetad of the `content type` fields.

**Comment by abhiabhi94** [comment]
I think we can move the option of adding flag to a separate issue for now.

**Comment by Radi85** [comment]
This will be closed and a new issue for the flagging will be opened.
