### ISSUE TITLE
Conflict with some third party library when using drf-yasg

### ISSUE THREAD

**Issue by khashashin** [Radi85/Comment#98]
**Environment**
* python 3.8
* django 3.1
* django-comments-dab 2.0.0

**Describe the bug**
I use django comments library from third party developers in my project and recently decided to add `drf-yasg`. However I get an error after configuring it and opening the endpoint `/swagger':

```
drf_yasg.errors.SwaggerGenerationError: Schema for <class 'djoser.serializers.UserSerializer'> would override distinct serializer <class 'comment.api.serializers.UserSerializer'> because they implicitly share the same ref_name; explicitly set the ref_name attribute on both serializers' Meta classes
```

Is there any way to add this `ref_name` attribute in to userserializer class of `comment` and/or `djoser`?

**To Reproduce**
Steps to reproduce the behavior (if not an installation or configuration issue):
1. Install djoser and configure it
2. install comment and configure it
3. install drf-yasg, configure it and try to open the `swagger` endpoint that is described by drf-yasg library

**Comment by abhiabhi94** [comment]
As far as I can see this error directly concerns `django-yasg`. 

Does the link https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.inspectors.InlineSerializerInspector solve your issue?

**Comment by khashashin** [comment]
Sorry, I didn't mean that this is a problem comment, but maybe is there to provide additional attributes in to meta class? Provided link by you, solves only partial problem and I get more issues if I use this configuration.

**Comment by Radi85** [comment]
@khashashin Thanks for the feedback!
I would suggest to add `DAB` suffix to the classes that might share the same name with othe apps. I.e. `UserSerializerDAB`.

**Comment by khashashin** [comment]
@Radi85 yes, definitely, if there is no backwards compatibility problems I'd suggest to do so.

**Comment by abhiabhi94** [comment]
I don't really completely understand how `drf-yasg` works but won't it be a better thing if they just added the prefix of the app name to the `serializer` class?

In general apps will have a `UserSerializer` especially they are using users, so still will obviously have issues there. I am not sure this should be handled at our level.

I might be miss something very basic here but may appear dumb.

**Comment by khashashin** [comment]
@abhiabhi94 I think if you are targeting to give users REST access to your DAB-Comment it is good practice to avoid future conflicts with other stuff around here and add some kind of prefixes/postfixes everywhere where is is possible.

**Comment by abhiabhi94** [comment]
> I think if you are targeting to give users REST access to your DAB-Comment it is good practice to avoid future conflicts with other stuff around here and add some kind of prefixes/postfixes everywhere where is is possible.

@khashashin yes, I completely agree with you on this. The point that I'm trying to make it we can obviously solve this issue at our end but what if there are multiple other serializers from third party applications that have the same issue? I just think it would be better if the problem is solved by just prefixing the app name with the serializer, pretty similar to what django does when it forms database tables from model classes.

**Comment by Radi85** [comment]
In fact my proposal is to add a postfix ONLY to the name of classes that might other apps use the same name such as `UserSerializer`.
